---
name: CI/CD
on:
  push:
    paths:
    - '.github/workflows/cicd.yml'
    - 'bin/*'
    - 'cf/**'
    - 'cmd/**'
    - 'templates/**'
    - '**Dockerfile'
    - 'Makefile*'
  workflow_dispatch:
  repository_dispatch:
    types: [update-cicd]

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: jmpa-io/roots/.github/workflows/lint.yml@main
    secrets: inherit

  test:
    uses: jmpa-io/roots/.github/workflows/test.yml@main
    secrets: inherit

  post-to-slack:
    needs: [lint, test]
    if: always()
    uses: jmpa-io/roots/.github/workflows/post-to-slack.yml@main
    secrets: inherit
