---
name: CI/CD
on:
  push:
    paths:
    - '.github/workflows/cicd.yml'
    - 'bin/*'
    - 'cf/**'
    - 'cmd/**'
    - 'templates/**'
    - '**Dockerfile'
    - 'Makefile*'
  workflow_dispatch:
  repository_dispatch:
    types: [update-cicd]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  lint:
    uses: jmpa-io/pipelines/.github/workflows/10-lint.yml@main
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  test:
    uses: jmpa-io/pipelines/.github/workflows/20-test.yml@main
    with:
      with-code-coverage: true
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  post-to-slack:
    needs: [lint, test]
    if: always()
    uses: jmpa-io/pipelines/.github/workflows/99-post-to-slack.yml@main
    secrets:
      WEBHOOK: ${{ secrets.SLACK_GITHUB_NOTIFICATIONS_WEBHOOK }}

